# Generated by Django 3.0.5 on 2020-04-29 03:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='The slug must be unique, it will be generated automatically if the field is blank.', unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='The slug must be unique, it will be generated automatically if the field is blank.', unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='products')),
                ('school_type', models.CharField(choices=[('PR', 'praktijkonderwijs'), ('VMBO', 'vmbo'), ('MBO', 'mbo'), ('HBO', 'hbo'), ('OP', 'opleidingsbedrijf')], max_length=48)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='Date published')),
                ('end_at', models.DateTimeField(verbose_name='Publishing end date')),
                ('categories', models.ManyToManyField(to='products.Category')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Supplier')),
            ],
        ),
    ]
